[project]
name = "ai-agents-development"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.4"
dependencies = [
    "anthropic[aiohttp]>=0.116.0",
    "async>=0.6.2",
    "httpx[socks]>=0.28.1",
    "openai>=2.45.0",
    "python-dotenv>=1.2.2",
]
